spring:
  h2:
    console:
      enabled: true
      settings.trace: false
      settings.web-allow-others: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:./test;
    username: sa
    password:
